### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by XiaoDouZiQwQ** [DreamVoid/Whitelist4QQ#13]
"Whitelist4QQ v1.0" has registered a listener for me.dreamvoid.miraimc.bukkit.event.MiraiGroupMemberLeaveEvent on method "public void me.dreamvoid.whitelist4qq.bukkit.BukkitPlugin$BotEvent.onGroupQuit(me.dreamvoid.miraimc.bukkit.event.MiraiGroupMemberLeaveEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [xingxing520, DreamVoid].

**Comment by DreamVoid** [comment]
别用太新的版本
