### ISSUE TITLE
发送“绑定”后台报错

### ISSUE THREAD

**Issue by CrnEilns** [DreamVoid/Whitelist4QQ#14]
如题
![image](https://user-images.githubusercontent.com/104747696/179385371-f6c18122-3f42-4022-908d-5b9e3bc63bca.png)
MiraiMC的 legacy-event-support设置为true

**Comment by DreamVoid** [comment]
稍后插件会适配MiraiMC 1.7

**Comment by CrnEilns** [comment]
可以催更么？（
