### ISSUE TITLE
1.19purpur 绑定漏洞 不加绑定名字也可以进行绑定

### ISSUE THREAD

**Issue by 848244210** [DreamVoid/Whitelist4QQ#18]
在 不使用MiraiMC的数据库而改为插件自存储 的情况下不加绑定名字也可以进行绑定

name:
- xlive2233
- minatiaquada
- xlive22332997
- aquanyanyanya
- Shiko_Official
- An_muxi
- KisugiAkira
- ''
- Heitu_Aasa
- Heitu_Sakirua
 

如上面的-“”

**Comment by DreamVoid** [comment]
无修复必要
