### ISSUE TITLE
意见建议

### ISSUE THREAD

**Issue by xiaohangDAD** [DreamVoid/Whitelist4QQ#3]
支持申请白名单ID正则校验防止中文ID、超短ID、超长ID。
支持群名片比对，让玩家将群名片修改为游戏ID。
支持把机器人QQ反馈信息 调整为服务器反馈信息防止被腾讯当广告机器人封号。

**Comment by DreamVoid** [comment]
第一条不考虑，本插件优先考虑正版服务器，任何一个没有被插件乱改的服务器这三种ID都不可能成功进入
第二、三条会考虑

**Comment by DreamVoid** [comment]
第二条不考虑，没有实际意义
第三条无法实现
