### ISSUE TITLE
什么时候适配 MiraiMC 1.8.1 并且支持 velocity

### ISSUE THREAD

**Issue by 93938791** [DreamVoid/Whitelist4QQ#33]
**_### 什么时候适配 MiraiMC 1.8.1 并且支持 velocity_**
![image](https://github.com/DreamVoid/Whitelist4QQ/assets/111562884/7a33a03e-1247-4e84-8c12-d13ec2bb8f48)

**Comment by DreamVoid** [comment]
我去，我还有这插件啊
有空就整，最近研究python

**Comment by 93938791** [comment]
> 我去，我还有这插件啊 有空就整，最近研究python

期待 (*❦ω❦)

**Comment by 93938791** [comment]
等不上了 T_T
