### ISSUE TITLE
选择使用id保存而非uuid/增加指令

### ISSUE THREAD

**Issue by LLF0421** [DreamVoid/Whitelist4QQ#5]
1.服务器未开启正版验证,正版玩家在群内申请白名单后,会出现存储的uuid和实际进入在游戏内的uuid不同,导致验证失败无法进入.
希望能做个开关(布尔)选择是否使用id而非uuid保存玩家信息.
2.增加一个可以手动删除玩家信息的指令(监听q群或者游戏指令),对id相关数据或qq号相关数据进行删除(现在需要删除数据只能连接数据库删除记录,部分用户不会操作)

ps:希望数据库可以独立设置,独立于miraimc的数据库设置

**Comment by ddos-ling** [comment]
遇到同样的问题，很难受
现在只能说想通过去重新编译解决，但是作者没打注释，找不到绑定哪那个类

**Comment by DreamVoid** [comment]
> 遇到同样的问题，很难受
> 现在只能说想通过去重新编译解决，但是作者没打注释，找不到绑定哪那个类

主要处理操作的就BukkitPlugin，改这个就是

**Comment by ddos-ling** [comment]
> > 遇到同样的问题，很难受
> > 现在只能说想通过去重新编译解决，但是作者没打注释，找不到绑定哪那个类
> 
> 主要处理操作的就BukkitPlugin，改这个就是

我刚刚改了一下，刚刚重构完
希望作者能在下一个版本中解决这个问题

**Comment by Shizuri23** [comment]
> > > 遇到同样的问题，很难受
> > > 现在只能说想通过去重新编译解决，但是作者没打注释，找不到绑定哪那个类
> > 
> > 
> > 主要处理操作的就BukkitPlugin，改这个就是
> 
> 我刚刚改了一下，刚刚重构完 希望作者能在下一个版本中解决这个问题

能分享一下你的重构版吗？我不太懂代码无法自己进行重构

**Comment by LittleHed** [comment]
同求...

**Comment by ddos-ling** [comment]
统一回复一下，我这个重构版加入了挺多奇奇怪怪的东西，和依赖，你们可能用不了
我等下构建好了放链接出来

**Comment by xiaobao4909** [comment]
> 统一回复一下，我这个重构版加入了挺多奇奇怪怪的东西，和依赖，你们可能用不了 我等下构建好了放链接出来

什么时候放出你的重构版啊 急需 什么时候啊 在mcbbs发个帖吧

**Comment by xiaobao4909** [comment]
> 统一回复一下，我这个重构版加入了挺多奇奇怪怪的东西，和依赖，你们可能用不了 我等下构建好了放链接出来

我小白不会改代码
