### ISSUE TITLE
申请未成功

### ISSUE THREAD

**Issue by xiaohuihui1022** [DreamVoid/Whitelist4QQ#6]
在按照MCBBS上的步骤一步一步来之后 在群里申请白名单没有任何的反馈信息
并且在后台都能打印出来我发的申请信息 但是机器人就是没有任何回应
插件貌似没有日志文件
望解决

**Comment by DreamVoid** [comment]
你说，有没有一种可能，是机器人被腾讯屏蔽了。
wiki.miraimc.dreamvoid.ml

**Comment by unusuallman** [comment]
我连机器人都没有反应
