### ISSUE TITLE
Whitelist4QQ的一个bug

### ISSUE THREAD

**Issue by YoruSakura** [DreamVoid/Whitelist4QQ#8]
玩家已经在群内通过机器人绑定游戏账号，但依然出现没有申请白名单导致进不去。在删除数据库重新生成文件之后，玩家再次绑定可以正常进服游玩。但是，在登录服关闭再打开之后，之前通过验证的玩家可以正常进入服务器，而新绑定的玩家在绑定之后会显示没有白名单进不去游戏，希望这个bug能修复一下。

**Comment by DreamVoid** [comment]
不处理任何盗版服务器的问题。
